[build]
  command = "npm run build"
  publish = "dist"

# Use Node 20 LTS for stable builds
[build.environment]
  NODE_VERSION = "20"

# Proxy API to your Render backend (REPLACE the URL below with your real backend URL)
[[redirects]]
  from = "/api/*"
  to = "https://YOUR-RENDER-BACKEND.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback so React Router works on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
